### PR TITLE
ru translation

### PR DESCRIPTION
**Pull request by stokito**

### CODE REVIEW

**Comment by phpbg** [comment]
Hi, thank you for your help!

Would you mind also updating:
* ‘app/build.gradle‘: update ‘resourceConfigurations += ["en", "fr", "de"]‘
* ‘res/xml/locales_config.xml‘ : add a locale entry

I'll try to add some tips in readme for next translators...

**Comment by stokito** [comment]
Ok, will do that in a hour. Or you can merge and make this uourself if you in hurry

**Comment by stokito** [comment]
pls merge

**Comment by phpbg** [comment]
Many thanks, merging right now

**Pull request merged**
